version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/dso101_db
    volumes:
      - bmi_data:/app/data

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dso101_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - bmi_backup:/var/lib/postgresql/bmi_backup
    ports:
      - "5432:5432"

  test:
    build: ./backend
    command: npm test
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/dso101_db
    profiles:
      - testing

volumes:
  postgres_data:
  bmi_data:
  bmi_backup: